### ISSUE TITLE
Add Cluster Name to kwatch notifications

### ISSUE THREAD

**Issue by Anindya-Banerjee** [abahmed/kwatch#137]
Our environments consist of hundreds of clusters. We generally have the daemonsets running on them. So, when a daemonset pod crashes. its very hard to figure out on which cluster it crashed since the namespace its deployed to will be the same accross all clusters. For example, fluent-bit will be deployed to all clusters in the same namespace. Can the cluster name please be added to the kwatch notifications? This would help us immensely.

**Comment by drzero42** [comment]
@Anindya-Banerjee I would also love to see the ability to add a clustername to kwatch notifications. As a work-around we have chosen to configure custom titles to the Slack messages that KWatch sends us.
From config.yaml:
```
          alert:
            slack:
              webhook: ${address}
              title: ":red_circle: kwatch detected a crash in pod on staging cluster"
```
Perhaps that could also help you?
