### ISSUE TITLE
ignoreContainerNames is not working

### ISSUE THREAD

**Issue by adamw-linadm** [abahmed/kwatch#166]
**Describe the bug**
ignoreContainerNames setting in configuration file  is not working.

**To Reproduce**
Use config with defined ignoreContainerNames eg.:
```
/ # cat /config/config.yaml 
maxRecentLogLines: 10
ignoreFailedGracefulShutdown: true
ignoreContainerNames:
  - article-extractor
alert:
  slack:
    webhook: https://hooks.slack.com/services/XXX

```

**Expected behavior**
Don't send notification about ignored container

**Actual behavior**
`time="2022-11-15T13:58:52Z" level=info msg="sending event: {Name:article-extractor-57b7d64674-xl7wd Container:article-extractor Namespace:services Reason:CrashLoopBackOff Events:[2022-11-15 13:52:17 +0000 UTC] Pulled Container.(trimed)"
`
**Version/Commit**
0.6.1
