### ISSUE TITLE
Helm chart does not output alert config for Telegram

### ISSUE THREAD

**Issue by drzero42** [abahmed/kwatch#178]
**Describe the bug**
When using the Helm chart with only the Telegram provider for alerts, no `alert` map is output. This is due to an if-statement that does not check for the `telegram` map [here](https://github.com/abahmed/kwatch/blob/main/deploy/chart/templates/configmap.yaml#L31)

**To Reproduce**
Deploy using the Helm chart with this set of values:
```
kwatch:
  config:
    configTemplate:
      alert:
        telegram:
          token: "${token}"
          chatId: "${chatId}"
```
The generated ConfigMap will not contain the expected `alert` section.

**Version/Commit**
Kwatch v0.6.1
