### ISSUE TITLE
Slack Message tittle and text not working after v0.7.0 upgrade

### ISSUE THREAD

**Issue by nporta-nep** [abahmed/kwatch#186]
**Describe the bug**
I have got a problem since the last release (v0.7) in that the slack messages now don't display the title or text I've configured in the kwatch config, they all just show the default text (kwatch detected a crash in the pod. && There is an issue with the container in a pod!). 
I even deleted kwatch entirely and did a fresh installation but the same thing happened. 

**To Reproduce**
Upgrade from v0.6 to v0.7 using:

`kubectl apply -f https://raw.githubusercontent.com/abahmed/kwatch/v0.7.0/deploy/deploy.yaml`

This is a config file I'm using:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: kwatch
  namespace: kwatch
data:
  config.yaml: |
    maxRecentLogLines: 8  
    ignoreFailedGracefulShutdown: true
    alert:
      slack:
        webhook: https://hooks.slack.com/services/xxxxxxxxxxxxx
        title: "There is a problem in Cluster XXXX" 
```

**Expected behavior**
I should be getting the correct title in the slack channel configured.

**Actual behavior**
I'm getting the default title in slack:

<img width="565" alt="image" src="https://user-images.githubusercontent.com/109222409/217581658-60074f83-e7f2-4f9c-9efa-61adbeb27d00.png">

I don't even have the red dot in the text, but I'm getting it anyways. 

**Version/Commit**
version 0.7.0
