### ISSUE TITLE
Chart configTemplate ignores clusterName and disableUpdateCheck

### ISSUE THREAD

**Issue by drzero42** [abahmed/kwatch#191]
**Describe the bug**
When using the Helm Chart, the `kwatch.config.configTemplate` section ignores setting `app.clusterName` and `upgrade.disableUpdateCheck`.

**To Reproduce**
Given this values file:
```
kwatch:
  config:
    configTemplate:
      app:
        clusterName: staging
      upgrader:
        disableUpdateCheck: true
```
Then run: `helm template kwatch . -f kwatch-values.yml | grep -A10 ConfigMap`
The output will be:
```
kind: ConfigMap
metadata:
  name: kwatch-kwatch
  namespace: default
data:
  config: |4
      maxRecentLogLines: 0
      ignoreFailedGracefulShutdown: false
      disableUpdateCheck: false
...
---
```

**Expected behavior**
Basically any and all values under `kwatch.config.configTemplate` should be put into the produced configMap.

**Version/Commit**
v0.8.0
