### ISSUE TITLE
Not receiving alerts from kwatch to teams

### ISSUE THREAD

**Issue by EzekielCodes** [abahmed/kwatch#204]
**Describe the bug**
I configured kwatch to send alerts to discord and teams but it only send to discord.

**To Reproduce**
To reproduce all you have to do it. apply the following config file to your kubernetes cluster adn make sure to update the webhook urls to match yours.

```
apiVersion: v1
kind: Namespace
metadata:
  name: kwatch
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kwatch
  namespace: kwatch
data:
  config.yaml: |
    alert:
      discord:
        webhook: https://discordapp.com/api/
      teams:
        webhook: https://hubkaho.webhook.office.com/
```

i am sure the error is with kwatch and not teams because i used postman to send a post request to the teams webhook and it works
**Expected behavior**
Expected behaviour is for discord alerts to work and teams  to work.

**Actual behavior**
actual behavior is that  discord alerts  work and teams dont.

**Version/Commit**
A version or commit of kwatch
