### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by rtzra** [abahmed/kwatch#85]
**Describe the bug**
Although I set Telegram channel webhook address in config.yaml file, I didn't get any notifications.

**Actual behavior**
My config:

```
data:
  config.yaml: |
    maxRecentLogLines: 10
    ignoreFailedGracefulShutdown: true
    alert:
      telegram:
          token: XXX
          chatId: -YYY
```

Error in pod logs:

> level=error msg="failed to send event with Telegram: Post \"https://api.telegram.org/botXXX/sendMessage\": x509: certificate signed by unknown authority"

**Expected behavior**
Should get kwatch notification to my Telegram channel.

**Version/Commit**
A version or commit of kwatch: 0.5.0
I'm run kwatch in k8s (1.17), as described in manual.
